### ISSUE TITLE
Outdated?

### ISSUE THREAD

**Issue by Niklas04** [sinricpro/language-files#17]
Is this repo still active?

I want to correct a bunch of german translations, but can't find all of them here

**Comment by kakopappa** [comment]
Yes.

I will update the repo and let you know.

Thanks

**Comment by kakopappa** [comment]
Hi @Niklas04 I have updated the language files. Please check

**Comment by Niklas04** [comment]
Perfect! Thanks

**Comment by Niklas04** [comment]
Hi @kakopappa ,

May can you update the files again, if there were some changes?
I want to correct some translations.

**Comment by kakopappa** [comment]
Hi @Niklas04 

Done. Thanks
